name: quality

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  quality:
    uses: benvon/reusable-workflows/.github/workflows/just-quality.yml@cd087ac5ce4adfc261f319ac5df2545e02ec60cc
